//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraWindows.WS2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esg.icpc.ola/", ConfigurationName="WS2.MaisFuncsSoap")]
    public interface MaisFuncsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esg.icpc.ola/MySoma", ReplyAction="*")]
        int MySoma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://esg.icpc.ola/MySoma", ReplyAction="*")]
        System.IAsyncResult BeginMySoma(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndMySoma(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esg.icpc.ola/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://esg.icpc.ola/Sub", ReplyAction="*")]
        System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSub(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaisFuncsSoapChannel : CalculadoraWindows.WS2.MaisFuncsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MySomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaisFuncsSoapClient : System.ServiceModel.ClientBase<CalculadoraWindows.WS2.MaisFuncsSoap>, CalculadoraWindows.WS2.MaisFuncsSoap {
        
        private BeginOperationDelegate onBeginMySomaDelegate;
        
        private EndOperationDelegate onEndMySomaDelegate;
        
        private System.Threading.SendOrPostCallback onMySomaCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubDelegate;
        
        private EndOperationDelegate onEndSubDelegate;
        
        private System.Threading.SendOrPostCallback onSubCompletedDelegate;
        
        public MaisFuncsSoapClient() {
        }
        
        public MaisFuncsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaisFuncsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaisFuncsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaisFuncsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<MySomaCompletedEventArgs> MySomaCompleted;
        
        public event System.EventHandler<SubCompletedEventArgs> SubCompleted;
        
        public int MySoma(int x, int y) {
            return base.Channel.MySoma(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMySoma(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMySoma(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndMySoma(System.IAsyncResult result) {
            return base.Channel.EndMySoma(result);
        }
        
        private System.IAsyncResult OnBeginMySoma(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginMySoma(x, y, callback, asyncState);
        }
        
        private object[] OnEndMySoma(System.IAsyncResult result) {
            int retVal = this.EndMySoma(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMySomaCompleted(object state) {
            if ((this.MySomaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MySomaCompleted(this, new MySomaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MySomaAsync(int x, int y) {
            this.MySomaAsync(x, y, null);
        }
        
        public void MySomaAsync(int x, int y, object userState) {
            if ((this.onBeginMySomaDelegate == null)) {
                this.onBeginMySomaDelegate = new BeginOperationDelegate(this.OnBeginMySoma);
            }
            if ((this.onEndMySomaDelegate == null)) {
                this.onEndMySomaDelegate = new EndOperationDelegate(this.OnEndMySoma);
            }
            if ((this.onMySomaCompletedDelegate == null)) {
                this.onMySomaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMySomaCompleted);
            }
            base.InvokeAsync(this.onBeginMySomaDelegate, new object[] {
                        x,
                        y}, this.onEndMySomaDelegate, this.onMySomaCompletedDelegate, userState);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSub(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSub(System.IAsyncResult result) {
            return base.Channel.EndSub(result);
        }
        
        private System.IAsyncResult OnBeginSub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSub(x, y, callback, asyncState);
        }
        
        private object[] OnEndSub(System.IAsyncResult result) {
            int retVal = this.EndSub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubCompleted(object state) {
            if ((this.SubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubCompleted(this, new SubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubAsync(int x, int y) {
            this.SubAsync(x, y, null);
        }
        
        public void SubAsync(int x, int y, object userState) {
            if ((this.onBeginSubDelegate == null)) {
                this.onBeginSubDelegate = new BeginOperationDelegate(this.OnBeginSub);
            }
            if ((this.onEndSubDelegate == null)) {
                this.onEndSubDelegate = new EndOperationDelegate(this.OnEndSub);
            }
            if ((this.onSubCompletedDelegate == null)) {
                this.onSubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubCompleted);
            }
            base.InvokeAsync(this.onBeginSubDelegate, new object[] {
                        x,
                        y}, this.onEndSubDelegate, this.onSubCompletedDelegate, userState);
        }
    }
}
