//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWS.WS3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="WS3.TextCasingSoapType")]
    public interface TextCasingSoapType {
        
        // CODEGEN: Generating message contract since element name sText from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.TitleCaseWordsWithTokenResponse TitleCaseWordsWithToken(ClienteWS.WS3.TitleCaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(ClienteWS.WS3.TitleCaseWordsWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.InvertStringCaseResponse InvertStringCase(ClienteWS.WS3.InvertStringCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertStringCaseResponse> InvertStringCaseAsync(ClienteWS.WS3.InvertStringCaseRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse InvertCaseFirstAdjustStringToPrevious(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse InvertCaseFirstAdjustStringToCurrent(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.AllUppercaseWithTokenResponse AllUppercaseWithToken(ClienteWS.WS3.AllUppercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(ClienteWS.WS3.AllUppercaseWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.AllLowercaseWithTokenResponse AllLowercaseWithToken(ClienteWS.WS3.AllLowercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(ClienteWS.WS3.AllLowercaseWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.UppercaseWordsWithTokenResponse UppercaseWordsWithToken(ClienteWS.WS3.UppercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(ClienteWS.WS3.UppercaseWordsWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ClienteWS.WS3.LowercaseWordsWithTokenResponse LowercaseWordsWithToken(ClienteWS.WS3.LowercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WS3.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(ClienteWS.WS3.LowercaseWordsWithTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.TitleCaseWordsWithTokenRequestBody Body;
        
        public TitleCaseWordsWithTokenRequest() {
        }
        
        public TitleCaseWordsWithTokenRequest(ClienteWS.WS3.TitleCaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public TitleCaseWordsWithTokenRequestBody() {
        }
        
        public TitleCaseWordsWithTokenRequestBody(string sText, string sToken) {
            this.sText = sText;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.TitleCaseWordsWithTokenResponseBody Body;
        
        public TitleCaseWordsWithTokenResponse() {
        }
        
        public TitleCaseWordsWithTokenResponse(ClienteWS.WS3.TitleCaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TitleCaseWordsWithTokenResult;
        
        public TitleCaseWordsWithTokenResponseBody() {
        }
        
        public TitleCaseWordsWithTokenResponseBody(string TitleCaseWordsWithTokenResult) {
            this.TitleCaseWordsWithTokenResult = TitleCaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCase", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertStringCaseRequestBody Body;
        
        public InvertStringCaseRequest() {
        }
        
        public InvertStringCaseRequest(ClienteWS.WS3.InvertStringCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertStringCaseRequestBody() {
        }
        
        public InvertStringCaseRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCaseResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertStringCaseResponseBody Body;
        
        public InvertStringCaseResponse() {
        }
        
        public InvertStringCaseResponse(ClienteWS.WS3.InvertStringCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertStringCaseResult;
        
        public InvertStringCaseResponseBody() {
        }
        
        public InvertStringCaseResponseBody(string InvertStringCaseResult) {
            this.InvertStringCaseResult = InvertStringCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPrevious", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequestBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousRequest() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequest(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPreviousResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponseBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousResponse() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponse(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToPreviousResult;
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody(string InvertCaseFirstAdjustStringToPreviousResult) {
            this.InvertCaseFirstAdjustStringToPreviousResult = InvertCaseFirstAdjustStringToPreviousResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrent", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequestBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentRequest() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequest(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrentResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponseBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentResponse() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponse(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToCurrentResult;
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody(string InvertCaseFirstAdjustStringToCurrentResult) {
            this.InvertCaseFirstAdjustStringToCurrentResult = InvertCaseFirstAdjustStringToCurrentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.AllUppercaseWithTokenRequestBody Body;
        
        public AllUppercaseWithTokenRequest() {
        }
        
        public AllUppercaseWithTokenRequest(ClienteWS.WS3.AllUppercaseWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllUppercaseWithTokenRequestBody() {
        }
        
        public AllUppercaseWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.AllUppercaseWithTokenResponseBody Body;
        
        public AllUppercaseWithTokenResponse() {
        }
        
        public AllUppercaseWithTokenResponse(ClienteWS.WS3.AllUppercaseWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllUppercaseWithTokenResult;
        
        public AllUppercaseWithTokenResponseBody() {
        }
        
        public AllUppercaseWithTokenResponseBody(string AllUppercaseWithTokenResult) {
            this.AllUppercaseWithTokenResult = AllUppercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.AllLowercaseWithTokenRequestBody Body;
        
        public AllLowercaseWithTokenRequest() {
        }
        
        public AllLowercaseWithTokenRequest(ClienteWS.WS3.AllLowercaseWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllLowercaseWithTokenRequestBody() {
        }
        
        public AllLowercaseWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.AllLowercaseWithTokenResponseBody Body;
        
        public AllLowercaseWithTokenResponse() {
        }
        
        public AllLowercaseWithTokenResponse(ClienteWS.WS3.AllLowercaseWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllLowercaseWithTokenResult;
        
        public AllLowercaseWithTokenResponseBody() {
        }
        
        public AllLowercaseWithTokenResponseBody(string AllLowercaseWithTokenResult) {
            this.AllLowercaseWithTokenResult = AllLowercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.UppercaseWordsWithTokenRequestBody Body;
        
        public UppercaseWordsWithTokenRequest() {
        }
        
        public UppercaseWordsWithTokenRequest(ClienteWS.WS3.UppercaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public UppercaseWordsWithTokenRequestBody() {
        }
        
        public UppercaseWordsWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.UppercaseWordsWithTokenResponseBody Body;
        
        public UppercaseWordsWithTokenResponse() {
        }
        
        public UppercaseWordsWithTokenResponse(ClienteWS.WS3.UppercaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UppercaseWordsWithTokenResult;
        
        public UppercaseWordsWithTokenResponseBody() {
        }
        
        public UppercaseWordsWithTokenResponseBody(string UppercaseWordsWithTokenResult) {
            this.UppercaseWordsWithTokenResult = UppercaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.LowercaseWordsWithTokenRequestBody Body;
        
        public LowercaseWordsWithTokenRequest() {
        }
        
        public LowercaseWordsWithTokenRequest(ClienteWS.WS3.LowercaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public LowercaseWordsWithTokenRequestBody() {
        }
        
        public LowercaseWordsWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ClienteWS.WS3.LowercaseWordsWithTokenResponseBody Body;
        
        public LowercaseWordsWithTokenResponse() {
        }
        
        public LowercaseWordsWithTokenResponse(ClienteWS.WS3.LowercaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LowercaseWordsWithTokenResult;
        
        public LowercaseWordsWithTokenResponseBody() {
        }
        
        public LowercaseWordsWithTokenResponseBody(string LowercaseWordsWithTokenResult) {
            this.LowercaseWordsWithTokenResult = LowercaseWordsWithTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextCasingSoapTypeChannel : ClienteWS.WS3.TextCasingSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextCasingSoapTypeClient : System.ServiceModel.ClientBase<ClienteWS.WS3.TextCasingSoapType>, ClienteWS.WS3.TextCasingSoapType {
        
        public TextCasingSoapTypeClient() {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCasingSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.TitleCaseWordsWithTokenResponse ClienteWS.WS3.TextCasingSoapType.TitleCaseWordsWithToken(ClienteWS.WS3.TitleCaseWordsWithTokenRequest request) {
            return base.Channel.TitleCaseWordsWithToken(request);
        }
        
        public string TitleCaseWordsWithToken(string sText, string sToken) {
            ClienteWS.WS3.TitleCaseWordsWithTokenRequest inValue = new ClienteWS.WS3.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            ClienteWS.WS3.TitleCaseWordsWithTokenResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).TitleCaseWordsWithToken(inValue);
            return retVal.Body.TitleCaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.TitleCaseWordsWithTokenResponse> ClienteWS.WS3.TextCasingSoapType.TitleCaseWordsWithTokenAsync(ClienteWS.WS3.TitleCaseWordsWithTokenRequest request) {
            return base.Channel.TitleCaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(string sText, string sToken) {
            ClienteWS.WS3.TitleCaseWordsWithTokenRequest inValue = new ClienteWS.WS3.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).TitleCaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.InvertStringCaseResponse ClienteWS.WS3.TextCasingSoapType.InvertStringCase(ClienteWS.WS3.InvertStringCaseRequest request) {
            return base.Channel.InvertStringCase(request);
        }
        
        public string InvertStringCase(string sAString) {
            ClienteWS.WS3.InvertStringCaseRequest inValue = new ClienteWS.WS3.InvertStringCaseRequest();
            inValue.Body = new ClienteWS.WS3.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            ClienteWS.WS3.InvertStringCaseResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertStringCase(inValue);
            return retVal.Body.InvertStringCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertStringCaseResponse> ClienteWS.WS3.TextCasingSoapType.InvertStringCaseAsync(ClienteWS.WS3.InvertStringCaseRequest request) {
            return base.Channel.InvertStringCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.InvertStringCaseResponse> InvertStringCaseAsync(string sAString) {
            ClienteWS.WS3.InvertStringCaseRequest inValue = new ClienteWS.WS3.InvertStringCaseRequest();
            inValue.Body = new ClienteWS.WS3.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertStringCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse ClienteWS.WS3.TextCasingSoapType.InvertCaseFirstAdjustStringToPrevious(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToPrevious(request);
        }
        
        public string InvertCaseFirstAdjustStringToPrevious(string sAString) {
            ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPrevious(inValue);
            return retVal.Body.InvertCaseFirstAdjustStringToPreviousResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse> ClienteWS.WS3.TextCasingSoapType.InvertCaseFirstAdjustStringToPreviousAsync(ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToPreviousAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(string sAString) {
            ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ClienteWS.WS3.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPreviousAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse ClienteWS.WS3.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrent(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToCurrent(request);
        }
        
        public string InvertCaseFirstAdjustStringToCurrent(string sAString) {
            ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrent(inValue);
            return retVal.Body.InvertCaseFirstAdjustStringToCurrentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse> ClienteWS.WS3.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrentAsync(ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToCurrentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(string sAString) {
            ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ClienteWS.WS3.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.AllUppercaseWithTokenResponse ClienteWS.WS3.TextCasingSoapType.AllUppercaseWithToken(ClienteWS.WS3.AllUppercaseWithTokenRequest request) {
            return base.Channel.AllUppercaseWithToken(request);
        }
        
        public string AllUppercaseWithToken(string sAString, string sToken) {
            ClienteWS.WS3.AllUppercaseWithTokenRequest inValue = new ClienteWS.WS3.AllUppercaseWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ClienteWS.WS3.AllUppercaseWithTokenResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).AllUppercaseWithToken(inValue);
            return retVal.Body.AllUppercaseWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.AllUppercaseWithTokenResponse> ClienteWS.WS3.TextCasingSoapType.AllUppercaseWithTokenAsync(ClienteWS.WS3.AllUppercaseWithTokenRequest request) {
            return base.Channel.AllUppercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(string sAString, string sToken) {
            ClienteWS.WS3.AllUppercaseWithTokenRequest inValue = new ClienteWS.WS3.AllUppercaseWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).AllUppercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.AllLowercaseWithTokenResponse ClienteWS.WS3.TextCasingSoapType.AllLowercaseWithToken(ClienteWS.WS3.AllLowercaseWithTokenRequest request) {
            return base.Channel.AllLowercaseWithToken(request);
        }
        
        public string AllLowercaseWithToken(string sAString, string sToken) {
            ClienteWS.WS3.AllLowercaseWithTokenRequest inValue = new ClienteWS.WS3.AllLowercaseWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ClienteWS.WS3.AllLowercaseWithTokenResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).AllLowercaseWithToken(inValue);
            return retVal.Body.AllLowercaseWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.AllLowercaseWithTokenResponse> ClienteWS.WS3.TextCasingSoapType.AllLowercaseWithTokenAsync(ClienteWS.WS3.AllLowercaseWithTokenRequest request) {
            return base.Channel.AllLowercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(string sAString, string sToken) {
            ClienteWS.WS3.AllLowercaseWithTokenRequest inValue = new ClienteWS.WS3.AllLowercaseWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).AllLowercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.UppercaseWordsWithTokenResponse ClienteWS.WS3.TextCasingSoapType.UppercaseWordsWithToken(ClienteWS.WS3.UppercaseWordsWithTokenRequest request) {
            return base.Channel.UppercaseWordsWithToken(request);
        }
        
        public string UppercaseWordsWithToken(string sAString, string sToken) {
            ClienteWS.WS3.UppercaseWordsWithTokenRequest inValue = new ClienteWS.WS3.UppercaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ClienteWS.WS3.UppercaseWordsWithTokenResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).UppercaseWordsWithToken(inValue);
            return retVal.Body.UppercaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.UppercaseWordsWithTokenResponse> ClienteWS.WS3.TextCasingSoapType.UppercaseWordsWithTokenAsync(ClienteWS.WS3.UppercaseWordsWithTokenRequest request) {
            return base.Channel.UppercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(string sAString, string sToken) {
            ClienteWS.WS3.UppercaseWordsWithTokenRequest inValue = new ClienteWS.WS3.UppercaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).UppercaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WS3.LowercaseWordsWithTokenResponse ClienteWS.WS3.TextCasingSoapType.LowercaseWordsWithToken(ClienteWS.WS3.LowercaseWordsWithTokenRequest request) {
            return base.Channel.LowercaseWordsWithToken(request);
        }
        
        public string LowercaseWordsWithToken(string sAString, string sToken) {
            ClienteWS.WS3.LowercaseWordsWithTokenRequest inValue = new ClienteWS.WS3.LowercaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ClienteWS.WS3.LowercaseWordsWithTokenResponse retVal = ((ClienteWS.WS3.TextCasingSoapType)(this)).LowercaseWordsWithToken(inValue);
            return retVal.Body.LowercaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WS3.LowercaseWordsWithTokenResponse> ClienteWS.WS3.TextCasingSoapType.LowercaseWordsWithTokenAsync(ClienteWS.WS3.LowercaseWordsWithTokenRequest request) {
            return base.Channel.LowercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WS3.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(string sAString, string sToken) {
            ClienteWS.WS3.LowercaseWordsWithTokenRequest inValue = new ClienteWS.WS3.LowercaseWordsWithTokenRequest();
            inValue.Body = new ClienteWS.WS3.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ClienteWS.WS3.TextCasingSoapType)(this)).LowercaseWordsWithTokenAsync(inValue);
        }
    }
}
