//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraWindows.WSExterno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esp.ipca.pt/", ConfigurationName="WSExterno.CalcSoap")]
    public interface CalcSoap {
        
        // CODEGEN: Generating message contract since element name OlaResult from namespace http://esp.ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Ola", ReplyAction="*")]
        CalculadoraWindows.WSExterno.OlaResponse Ola(CalculadoraWindows.WSExterno.OlaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://esp.ipca.pt/Ola", ReplyAction="*")]
        System.IAsyncResult BeginOla(CalculadoraWindows.WSExterno.OlaRequest request, System.AsyncCallback callback, object asyncState);
        
        CalculadoraWindows.WSExterno.OlaResponse EndOla(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        System.IAsyncResult BeginSoma(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSoma(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OlaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ola", Namespace="http://esp.ipca.pt/", Order=0)]
        public CalculadoraWindows.WSExterno.OlaRequestBody Body;
        
        public OlaRequest() {
        }
        
        public OlaRequest(CalculadoraWindows.WSExterno.OlaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OlaRequestBody {
        
        public OlaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OlaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OlaResponse", Namespace="http://esp.ipca.pt/", Order=0)]
        public CalculadoraWindows.WSExterno.OlaResponseBody Body;
        
        public OlaResponse() {
        }
        
        public OlaResponse(CalculadoraWindows.WSExterno.OlaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://esp.ipca.pt/")]
    public partial class OlaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OlaResult;
        
        public OlaResponseBody() {
        }
        
        public OlaResponseBody(string OlaResult) {
            this.OlaResult = OlaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSoapChannel : CalculadoraWindows.WSExterno.CalcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OlaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OlaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSoapClient : System.ServiceModel.ClientBase<CalculadoraWindows.WSExterno.CalcSoap>, CalculadoraWindows.WSExterno.CalcSoap {
        
        private BeginOperationDelegate onBeginOlaDelegate;
        
        private EndOperationDelegate onEndOlaDelegate;
        
        private System.Threading.SendOrPostCallback onOlaCompletedDelegate;
        
        private BeginOperationDelegate onBeginSomaDelegate;
        
        private EndOperationDelegate onEndSomaDelegate;
        
        private System.Threading.SendOrPostCallback onSomaCompletedDelegate;
        
        public CalcSoapClient() {
        }
        
        public CalcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<OlaCompletedEventArgs> OlaCompleted;
        
        public event System.EventHandler<SomaCompletedEventArgs> SomaCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraWindows.WSExterno.OlaResponse CalculadoraWindows.WSExterno.CalcSoap.Ola(CalculadoraWindows.WSExterno.OlaRequest request) {
            return base.Channel.Ola(request);
        }
        
        public string Ola() {
            CalculadoraWindows.WSExterno.OlaRequest inValue = new CalculadoraWindows.WSExterno.OlaRequest();
            inValue.Body = new CalculadoraWindows.WSExterno.OlaRequestBody();
            CalculadoraWindows.WSExterno.OlaResponse retVal = ((CalculadoraWindows.WSExterno.CalcSoap)(this)).Ola(inValue);
            return retVal.Body.OlaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CalculadoraWindows.WSExterno.CalcSoap.BeginOla(CalculadoraWindows.WSExterno.OlaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOla(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginOla(System.AsyncCallback callback, object asyncState) {
            CalculadoraWindows.WSExterno.OlaRequest inValue = new CalculadoraWindows.WSExterno.OlaRequest();
            inValue.Body = new CalculadoraWindows.WSExterno.OlaRequestBody();
            return ((CalculadoraWindows.WSExterno.CalcSoap)(this)).BeginOla(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraWindows.WSExterno.OlaResponse CalculadoraWindows.WSExterno.CalcSoap.EndOla(System.IAsyncResult result) {
            return base.Channel.EndOla(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndOla(System.IAsyncResult result) {
            CalculadoraWindows.WSExterno.OlaResponse retVal = ((CalculadoraWindows.WSExterno.CalcSoap)(this)).EndOla(result);
            return retVal.Body.OlaResult;
        }
        
        private System.IAsyncResult OnBeginOla(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginOla(callback, asyncState);
        }
        
        private object[] OnEndOla(System.IAsyncResult result) {
            string retVal = this.EndOla(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOlaCompleted(object state) {
            if ((this.OlaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OlaCompleted(this, new OlaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OlaAsync() {
            this.OlaAsync(null);
        }
        
        public void OlaAsync(object userState) {
            if ((this.onBeginOlaDelegate == null)) {
                this.onBeginOlaDelegate = new BeginOperationDelegate(this.OnBeginOla);
            }
            if ((this.onEndOlaDelegate == null)) {
                this.onEndOlaDelegate = new EndOperationDelegate(this.OnEndOla);
            }
            if ((this.onOlaCompletedDelegate == null)) {
                this.onOlaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOlaCompleted);
            }
            base.InvokeAsync(this.onBeginOlaDelegate, null, this.onEndOlaDelegate, this.onOlaCompletedDelegate, userState);
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSoma(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSoma(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSoma(System.IAsyncResult result) {
            return base.Channel.EndSoma(result);
        }
        
        private System.IAsyncResult OnBeginSoma(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSoma(x, y, callback, asyncState);
        }
        
        private object[] OnEndSoma(System.IAsyncResult result) {
            int retVal = this.EndSoma(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSomaCompleted(object state) {
            if ((this.SomaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SomaCompleted(this, new SomaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SomaAsync(int x, int y) {
            this.SomaAsync(x, y, null);
        }
        
        public void SomaAsync(int x, int y, object userState) {
            if ((this.onBeginSomaDelegate == null)) {
                this.onBeginSomaDelegate = new BeginOperationDelegate(this.OnBeginSoma);
            }
            if ((this.onEndSomaDelegate == null)) {
                this.onEndSomaDelegate = new EndOperationDelegate(this.OnEndSoma);
            }
            if ((this.onSomaCompletedDelegate == null)) {
                this.onSomaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSomaCompleted);
            }
            base.InvokeAsync(this.onBeginSomaDelegate, new object[] {
                        x,
                        y}, this.onEndSomaDelegate, this.onSomaCompletedDelegate, userState);
        }
    }
}
