//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraWindows.WS3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ipca.pt/ws/", ConfigurationName="WS3.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetAllHoteisClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CalculadoraWindows.WS3.HotelClass[] GetAllHoteisClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetAllHoteisClass", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculadoraWindows.WS3.HotelClass[]> GetAllHoteisClassAsync();
        
        // CODEGEN: Parameter 'GetAllHoteisClassIIResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetAllHoteisClassII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CalculadoraWindows.WS3.GetAllHoteisClassIIResponse GetAllHoteisClassII(CalculadoraWindows.WS3.GetAllHoteisClassIIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetAllHoteisClassII", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetAllHoteisClassIIResponse> GetAllHoteisClassIIAsync(CalculadoraWindows.WS3.GetAllHoteisClassIIRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (ipca:http://www.ipca.pt/ws/HotelClasse) does not match the default value (http://www.ipca.pt/ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetHotelClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="HotelNovo")]
        CalculadoraWindows.WS3.GetHotelClassResponse GetHotelClass(CalculadoraWindows.WS3.GetHotelClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetHotelClass", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetHotelClassResponse> GetHotelClassAsync(CalculadoraWindows.WS3.GetHotelClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetHotelClassII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHotelClassII();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/ws/GetHotelClassII", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetHotelClassIIAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ipca:http://www.ipca.pt/ws/HotelClasse")]
    public partial class HotelClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomField;
        
        private string cidField;
        
        private int capField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ipca.pt/ws/HotelClasse", Order=0)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ipca.pt/ws/HotelClasse", Order=1)]
        public string cid {
            get {
                return this.cidField;
            }
            set {
                this.cidField = value;
                this.RaisePropertyChanged("cid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ipca.pt/ws/HotelClasse")]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllHoteisClassII", WrapperNamespace="http://www.ipca.pt/ws/", IsWrapped=true)]
    public partial class GetAllHoteisClassIIRequest {
        
        public GetAllHoteisClassIIRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllHoteisClassIIResponse", WrapperNamespace="http://www.ipca.pt/ws/", IsWrapped=true)]
    public partial class GetAllHoteisClassIIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ipca.pt/ws/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HotelClassII")]
        public System.Data.DataSet[] GetAllHoteisClassIIResult;
        
        public GetAllHoteisClassIIResponse() {
        }
        
        public GetAllHoteisClassIIResponse(System.Data.DataSet[] GetAllHoteisClassIIResult) {
            this.GetAllHoteisClassIIResult = GetAllHoteisClassIIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotelClass", WrapperNamespace="http://www.ipca.pt/ws/", IsWrapped=true)]
    public partial class GetHotelClassRequest {
        
        public GetHotelClassRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotelClassResponse", WrapperNamespace="http://www.ipca.pt/ws/", IsWrapped=true)]
    public partial class GetHotelClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ipca:http://www.ipca.pt/ws/HotelClasse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="ipca:http://www.ipca.pt/ws/HotelClasse")]
        public CalculadoraWindows.WS3.HotelClass HotelNovo;
        
        public GetHotelClassResponse() {
        }
        
        public GetHotelClassResponse(CalculadoraWindows.WS3.HotelClass HotelNovo) {
            this.HotelNovo = HotelNovo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CalculadoraWindows.WS3.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CalculadoraWindows.WS3.ServiceSoap>, CalculadoraWindows.WS3.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CalculadoraWindows.WS3.HotelClass[] GetAllHoteisClass() {
            return base.Channel.GetAllHoteisClass();
        }
        
        public System.Threading.Tasks.Task<CalculadoraWindows.WS3.HotelClass[]> GetAllHoteisClassAsync() {
            return base.Channel.GetAllHoteisClassAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraWindows.WS3.GetAllHoteisClassIIResponse CalculadoraWindows.WS3.ServiceSoap.GetAllHoteisClassII(CalculadoraWindows.WS3.GetAllHoteisClassIIRequest request) {
            return base.Channel.GetAllHoteisClassII(request);
        }
        
        public System.Data.DataSet[] GetAllHoteisClassII() {
            CalculadoraWindows.WS3.GetAllHoteisClassIIRequest inValue = new CalculadoraWindows.WS3.GetAllHoteisClassIIRequest();
            CalculadoraWindows.WS3.GetAllHoteisClassIIResponse retVal = ((CalculadoraWindows.WS3.ServiceSoap)(this)).GetAllHoteisClassII(inValue);
            return retVal.GetAllHoteisClassIIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetAllHoteisClassIIResponse> CalculadoraWindows.WS3.ServiceSoap.GetAllHoteisClassIIAsync(CalculadoraWindows.WS3.GetAllHoteisClassIIRequest request) {
            return base.Channel.GetAllHoteisClassIIAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetAllHoteisClassIIResponse> GetAllHoteisClassIIAsync() {
            CalculadoraWindows.WS3.GetAllHoteisClassIIRequest inValue = new CalculadoraWindows.WS3.GetAllHoteisClassIIRequest();
            return ((CalculadoraWindows.WS3.ServiceSoap)(this)).GetAllHoteisClassIIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculadoraWindows.WS3.GetHotelClassResponse CalculadoraWindows.WS3.ServiceSoap.GetHotelClass(CalculadoraWindows.WS3.GetHotelClassRequest request) {
            return base.Channel.GetHotelClass(request);
        }
        
        public CalculadoraWindows.WS3.HotelClass GetHotelClass() {
            CalculadoraWindows.WS3.GetHotelClassRequest inValue = new CalculadoraWindows.WS3.GetHotelClassRequest();
            CalculadoraWindows.WS3.GetHotelClassResponse retVal = ((CalculadoraWindows.WS3.ServiceSoap)(this)).GetHotelClass(inValue);
            return retVal.HotelNovo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetHotelClassResponse> CalculadoraWindows.WS3.ServiceSoap.GetHotelClassAsync(CalculadoraWindows.WS3.GetHotelClassRequest request) {
            return base.Channel.GetHotelClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculadoraWindows.WS3.GetHotelClassResponse> GetHotelClassAsync() {
            CalculadoraWindows.WS3.GetHotelClassRequest inValue = new CalculadoraWindows.WS3.GetHotelClassRequest();
            return ((CalculadoraWindows.WS3.ServiceSoap)(this)).GetHotelClassAsync(inValue);
        }
        
        public System.Data.DataSet GetHotelClassII() {
            return base.Channel.GetHotelClassII();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetHotelClassIIAsync() {
            return base.Channel.GetHotelClassIIAsync();
        }
    }
}
