//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWS.WSCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esp.ipca.pt/", ConfigurationName="WSCalc.CalcSoap")]
    public interface CalcSoap {
        
        // CODEGEN: Generating message contract since element name s from namespace http://esp.ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/ShowUpperCase", ReplyAction="*")]
        ClienteWS.WSCalc.ShowUpperCaseResponse ShowUpperCase(ClienteWS.WSCalc.ShowUpperCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/ShowUpperCase", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWS.WSCalc.ShowUpperCaseResponse> ShowUpperCaseAsync(ClienteWS.WSCalc.ShowUpperCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomaAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUpperCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUpperCase", Namespace="http://esp.ipca.pt/", Order=0)]
        public ClienteWS.WSCalc.ShowUpperCaseRequestBody Body;
        
        public ShowUpperCaseRequest() {
        }
        
        public ShowUpperCaseRequest(ClienteWS.WSCalc.ShowUpperCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://esp.ipca.pt/")]
    public partial class ShowUpperCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public ShowUpperCaseRequestBody() {
        }
        
        public ShowUpperCaseRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUpperCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUpperCaseResponse", Namespace="http://esp.ipca.pt/", Order=0)]
        public ClienteWS.WSCalc.ShowUpperCaseResponseBody Body;
        
        public ShowUpperCaseResponse() {
        }
        
        public ShowUpperCaseResponse(ClienteWS.WSCalc.ShowUpperCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://esp.ipca.pt/")]
    public partial class ShowUpperCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowUpperCaseResult;
        
        public ShowUpperCaseResponseBody() {
        }
        
        public ShowUpperCaseResponseBody(string ShowUpperCaseResult) {
            this.ShowUpperCaseResult = ShowUpperCaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSoapChannel : ClienteWS.WSCalc.CalcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSoapClient : System.ServiceModel.ClientBase<ClienteWS.WSCalc.CalcSoap>, ClienteWS.WSCalc.CalcSoap {
        
        public CalcSoapClient() {
        }
        
        public CalcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.WSCalc.ShowUpperCaseResponse ClienteWS.WSCalc.CalcSoap.ShowUpperCase(ClienteWS.WSCalc.ShowUpperCaseRequest request) {
            return base.Channel.ShowUpperCase(request);
        }
        
        public string ShowUpperCase(string s) {
            ClienteWS.WSCalc.ShowUpperCaseRequest inValue = new ClienteWS.WSCalc.ShowUpperCaseRequest();
            inValue.Body = new ClienteWS.WSCalc.ShowUpperCaseRequestBody();
            inValue.Body.s = s;
            ClienteWS.WSCalc.ShowUpperCaseResponse retVal = ((ClienteWS.WSCalc.CalcSoap)(this)).ShowUpperCase(inValue);
            return retVal.Body.ShowUpperCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.WSCalc.ShowUpperCaseResponse> ClienteWS.WSCalc.CalcSoap.ShowUpperCaseAsync(ClienteWS.WSCalc.ShowUpperCaseRequest request) {
            return base.Channel.ShowUpperCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WSCalc.ShowUpperCaseResponse> ShowUpperCaseAsync(string s) {
            ClienteWS.WSCalc.ShowUpperCaseRequest inValue = new ClienteWS.WSCalc.ShowUpperCaseRequest();
            inValue.Body = new ClienteWS.WSCalc.ShowUpperCaseRequestBody();
            inValue.Body.s = s;
            return ((ClienteWS.WSCalc.CalcSoap)(this)).ShowUpperCaseAsync(inValue);
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomaAsync(int x, int y) {
            return base.Channel.SomaAsync(x, y);
        }
    }
}
