//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaCalculadora.CalcWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esp.ipca.pt/", ConfigurationName="CalcWS.CalcSoap")]
    public interface CalcSoap {
        
        // CODEGEN: Generating message contract since element name OlaResult from namespace http://esp.ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Ola", ReplyAction="*")]
        NovaCalculadora.CalcWS.OlaResponse Ola(NovaCalculadora.CalcWS.OlaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Ola", ReplyAction="*")]
        System.Threading.Tasks.Task<NovaCalculadora.CalcWS.OlaResponse> OlaAsync(NovaCalculadora.CalcWS.OlaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esp.ipca.pt/Soma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomaAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OlaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ola", Namespace="http://esp.ipca.pt/", Order=0)]
        public NovaCalculadora.CalcWS.OlaRequestBody Body;
        
        public OlaRequest() {
        }
        
        public OlaRequest(NovaCalculadora.CalcWS.OlaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OlaRequestBody {
        
        public OlaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OlaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OlaResponse", Namespace="http://esp.ipca.pt/", Order=0)]
        public NovaCalculadora.CalcWS.OlaResponseBody Body;
        
        public OlaResponse() {
        }
        
        public OlaResponse(NovaCalculadora.CalcWS.OlaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://esp.ipca.pt/")]
    public partial class OlaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OlaResult;
        
        public OlaResponseBody() {
        }
        
        public OlaResponseBody(string OlaResult) {
            this.OlaResult = OlaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSoapChannel : NovaCalculadora.CalcWS.CalcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSoapClient : System.ServiceModel.ClientBase<NovaCalculadora.CalcWS.CalcSoap>, NovaCalculadora.CalcWS.CalcSoap {
        
        public CalcSoapClient() {
        }
        
        public CalcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NovaCalculadora.CalcWS.OlaResponse NovaCalculadora.CalcWS.CalcSoap.Ola(NovaCalculadora.CalcWS.OlaRequest request) {
            return base.Channel.Ola(request);
        }
        
        public string Ola() {
            NovaCalculadora.CalcWS.OlaRequest inValue = new NovaCalculadora.CalcWS.OlaRequest();
            inValue.Body = new NovaCalculadora.CalcWS.OlaRequestBody();
            NovaCalculadora.CalcWS.OlaResponse retVal = ((NovaCalculadora.CalcWS.CalcSoap)(this)).Ola(inValue);
            return retVal.Body.OlaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NovaCalculadora.CalcWS.OlaResponse> NovaCalculadora.CalcWS.CalcSoap.OlaAsync(NovaCalculadora.CalcWS.OlaRequest request) {
            return base.Channel.OlaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NovaCalculadora.CalcWS.OlaResponse> OlaAsync() {
            NovaCalculadora.CalcWS.OlaRequest inValue = new NovaCalculadora.CalcWS.OlaRequest();
            inValue.Body = new NovaCalculadora.CalcWS.OlaRequestBody();
            return ((NovaCalculadora.CalcWS.CalcSoap)(this)).OlaAsync(inValue);
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomaAsync(int x, int y) {
            return base.Channel.SomaAsync(x, y);
        }
    }
}
